// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package api

// SignInBadRequest sign-in時のBad Request
type SignInBadRequest struct {
	ErrorCode *string `json:"error_code,omitempty"`
}

// SignInRequest sign-in時のリクエストパラメータ
type SignInRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// SignInResponse sign-in時のレスポンス
type SignInResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
}

// PostApiSignInJSONRequestBody defines body for PostApiSignIn for application/json ContentType.
type PostApiSignInJSONRequestBody = SignInRequest
